require("Bennys.settings.globals")
require("Bennys.settings.opt")
require("Bennys.settings.autocmd")
require("Bennys.settings.options")
require("Bennys.settings.rsync")
local keys = require("Bennys.settings.keymaps")
require("util").mapKeys(keys)
